### ISSUE TITLE
Centos 7 - Systemd was not detected

### ISSUE THREAD

**Issue by mis4s** [monitoringartist/zabbix-systemd-monitoring#1]
Hi,

I got problems with Centos 7. On one vm work, another not. The error is 

> ZBX_NOTSUPPORTED: Systemd was not detected

I debug that my driver is "docker". In `/sys/fs/cgroup/cpuset` is `/sys/fs/cgroup/cpuset/docker` not `/sys/fs/cgroup/system.slice`. 

Any ideas to fix this?

```
$ docker -v 
Docker version 1.12.6, build 78d1802

$ docker info

Containers: 24
 Running: 2
 Paused: 0
 Stopped: 22
Images: 95
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:1-743346691-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 54.11 GB
 Data Space Total: 107.4 GB
 Data Space Available: 53.26 GB
 Metadata Space Used: 57.89 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.09 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.627 GiB
Name: XXXXXXXXXXXx
ID: XXXXXXXXXXX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Comment by jangaraj** [comment]
Unfortunately there is no way to fix it easily. Docker has a priority in the module (systemd is only secondary beta functionality), so module code needs a change in this case. I was thinking about exposing of cgroup.v1.[discovery, cpu, mem,... ] methods (for systemd, lxc, lxd,....). PR is welcome.

I'm closing this issue, because I don't think that this my implementation of systemd monitoring is optimal one. It's only secondary feature of docker monitoring module. I'm still happy to review any PR, which will solve this problem in the current module version.

I prefer using of sd-bus API - http://0pointer.net/blog/the-new-sd-bus-api-of-systemd.html. Required systemd 221+ can be problem for CentOS 7/RHEL 7, but Docker can solve it. I've made private POC Zabbix module with discovery method based on sd-bus API (interface `org.freedesktop.systemd1.Manager` and method `ListUnits`), which works fine also for unit/services in not running state:
```
systemd.dbus.discovery[<unit_filter>,<unit_state>]
systemd.dbus.discovery[.service,all]
```
